奈良追加します
iemeshi/registry pull request #14
Opened 2020-05-20 09:48 UTC by kwaka1208

まだ一件だけですが、データはこれから増やしていきます。

2020-05-20 09:55 UTC, miya0001 requested changes
ありがとうございます！

すいませんが、以下の内容の修正をお願いします。

* CNAME には、ドメイン名のみを指定できます。サブディレクトリには対応していませんので、Netlify 等の `xxxxx.netlify.app` のようなドメイン名が利用できるサービスをご利用いただけると幸いです。（そのほうがメンテナンスも簡単です。）
* 県全域だと大変かなと思いました。他の方でやりたい方が今後出てくるかもしれないですし、現状データの数も少ないので `奈良市` とかで限定していただけると幸いです。

2020-05-20 10:02 UTC, kamataryo requested changes
あと、CNAME なんですが、Netlify の場合は、Netlify のドメイン（`xxx.netlify.app`）、GitHub Pages でホストする場合は `ユーザー名.github.io` のようになります！

2020-05-20 10:02 UTC, kamataryo commented on apps.json
>    }
ありがとうございます！ここの行末にカンマを入れていただけますか？

2020-05-20 10:20 UTC, kwaka1208 commented
わかりました〜、失礼しました。 ^ ^;
地域については悩んだんですが、心当たりのあるところが点在してて...。
どうするか考えて、またPRします。

2020-06-27 18:39 UTC, miya0001 commented
一旦閉じますね。ありがとうございます。

2020-06-27 18:39 UTC, closed without merging

2020-06-27 20:44 UTC, kwaka1208 commented
はい、その後進んでいなくて申し訳ありません。 m(_ _)m